const OrderData=[
    {
        id:'1',
        name:"abdul",
        servicename:"haircut",
        price:"$5",
        date:'23/12/2020',
        time:"3:30PM",
        location:"Islamabad"
    },
    {
        id:'2',
        name:"abdul",
        servicename:"haircut",
        price:"$5",
        date:'23/12/2020',
        time:"3:30PM",
        location:"Islamabad"
    },
    {
        id:'3',
        name:"abdul",
        servicename:"haircut",
        price:"$5",
        date:'23/12/2020',
        time:"3:30PM",
        location:"Islamabad"
    },
    {
        id:'4',
        name:"abdul",
        servicename:"haircut",
        price:"$5",
        date:'23/12/2020',
        time:"3:30PM",
        location:"Islamabad"
    },
    {
        id:'5',
        name:"abdul",
        servicename:"haircut",
        price:"$5",
        date:'23/12/2020',
        time:"3:30PM",
        location:"Islamabad"
    },
]

export default OrderData;